[package]
name = "bot-3lc"
version = "1.0.0"
edition = "2024"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serenity = { version = "0.12", features = ["client", "gateway", "rustls_backend", "model"] }
poise = "0.6"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12"}
image = "0.25"
tempfile = "3.27.0"
